server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_authorization
    username: app
    password: app
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:3000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT_MS:1000}
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: ${REDIS_COMMAND_TIMEOUT:1s}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:1s}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    br.com.renan.corebanking: DEBUG
