server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_authorization
    username: app
    password: app
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    br.com.renan.corebanking: DEBUG
